import React from 'react';

function Osi() {
  return (
    <div className="UDP">
      <h1>12.UDP protokols</h1>
      <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>UDP (angļu: User Datagram Protocol — lietotāja datagrammu protokols) ir transporta slāņa protokols, kas nodrošina īsu ziņojumu (datagrammu) pārsūtīšanu no vienas sistēmas uz otru. UDP atšķirībā no TCP nenodrošina drošu un secīgu datu nogādi līdz galam. Datagrammas var pienākt sajauktā secībā, var dublēties vai var pazust. Šī iemesla dēļ UDP ir ātrāks un efektīvāks (vismaz programmām, kurām nevajag garantētu piegādi). UDP parasti lieto DNS, DHCP, VoIP un tīkla spēles.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>UDP, tāpat kā TCP, lieto portus, lai vienā datorā varētu darbināt vairākas programmas, kas lieto UDP. Portu lauku garums UDP paketes headerī ir 16 biti (tāpat kā TCP). Tas nozīmē, ka ir pieejami porti no 0 līdz 65535. Uz 0. portu neko nevar aizsūīt, to lieto tad, ja process, kas sūta paketi, negaida atbildi.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>UDP nodrošina ļoti vienkāršu intefeisu starp tīkla slāni un augšējā līmeņa protokoliem. UDP tikai nodrošina kontrolsummu (visai paketei), bet tā nav obligāta.</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Paketes hederī (galvenē) ir tikai 4 lauki, no kuriem divi nav obligāti (rozā):</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Source port</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;- šis lauks norāda no kura porta pakete ir tikusi nosūtīta (ja to lieto), ja to nelieto, tur jāieliek 0.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Destination port</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;- šis lauks norāda uz kuru portu attālinātajā sistēmā paketi jāpiegādā. Šis lauks ir obligāts.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Garums</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;- tas ir 16 bitu lauks, kas apraksta visas paketes garumu (baitos). Minimālais paketes garums ir 8 baiti, jo tas ir hedera garums. Šis lauks nosaka maksimālo teorētisko UDP datagrammas izmēru (65527).</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Kontrolsumma</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;- šo 16 bitu lauku lieto lai pārbaudītu vai paketē (un hederī) pārsūtīšanas laikā nav radušās kļūdas. To aprēķina blokam, kas sastāv no IP hedera, UDP hedera un UDP datiem. Ja aprēķinātā kontrolsumma ir visas 0, tad to nosūta kā visus 1. Ja kontrolsummu nelieto (šis nav obligāts lauks), tad to norāda kā visas 0. IPv6 gadījumā destination adress no IP hedera, ja lieto routing hederus ir pēdējā adrese no routing hedera, ja nelieto tad tā ir destination adress no IP hedera (tāpat kā IPv4 gadījumā).</span></p>
          </li>
        </ul>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>UDP lieto programmas, kurām ir nepieciešama vismazākā iespējamā latency (pat uz datu zuduma rēķina, tīkla traucējumu gadījumos) (VoIP, datorspēles (RTS, FPS un citas ātras spēles)), programmas, kurām jāapkalpo liels skaits maza izmēra pieprasījumu no liela daudzuma klientu (DNS, DHCP), jo, lai atvērtu TCP konnekciju ir nepieciešamas 3 paketes (lai korekti aizvērtu vajag vēl dažas), UDP visām komunikācijām pietiek ar vienu ienākošo un vienu izejošo paketi. Vēl UDP lieto programmas, kas darbojas ar ļoti ierobežotiem resursiem, (UDP vajag mazāk kā TCP) (TFTP, daļēji DHCP)(kad tos lieto lai ielādētu OS no tīkla).</span></p>
    </div>
  );
}

export default Osi;
