import React from 'react';

function Osi() {
  return (
    <div className="OSI">
      <h1>1.OSI, TCP/IP modeļi.</h1>
      <div>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ieguvumi izmantojot slāņotu modeli, lai aprakstītu tīkla protokolus un operācijas, iekļauj:</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Palīdzība protokolu dizainā, jo protokoliem, kas darbojas specifiskā slāni, ir definēta informācija, kuru viņi izmanto un definēta saskarne slāņiem augstāk un zemāk.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Konkurences veicināšana, jo produkti no dažādiem pārdevējiem strādā kopā.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Novērš tehnoloģijas vai spējas izmaiņas vienā slānī no ietekmēšanas sļānos lejā un augšā.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Sniedz kopēju valodu, lai aprakstīju tīklošanas funkcijas un spējas.</span></p>
          </li>
        </ul>
      </div>
      <div>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>TCP/IP modelis un OSI modelis ir galvenie modeļi, kas tiek izmantoti, lai aprakstītu tīkla funkcionalitāti. Katrs pārstāv slāņota tīklošanas modeļa tipu:</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Protokolu modelis – Šis modeļa tips tuvu sakrīt ar struktūru no konkrētas protokolu saimes. TCP/IP modelis ir protokolu modelis, jo tas apraksta funkcijas, kas notiek katrā protokolu slānī iekš TCP/IP protokolu kopuma. TCP/IP ir arī izmantots kā atsauces modelis.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Atsauces modelis jeb “Reference model” – Šis modeļa tips nodrošina pastāvīgumu starp visiem tīkla protokolu un pakalpojumu(services) tipiem, aprakstot, kas ir jādara noteiktā slānī, bet neapraksot kā tas ir jādara. OSI modelis ir plaši zināms starptīkla(internetwork) atsauces modelis, bet ir arī protokolu modelis OSI protokolu kopumam.</span></p>
          </li>
        </ul>
      </div>
      <h2>OSI modelis</h2>
      <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>1984. gadā tika publicēts OSI (Open System Interconnection) modelis, kas kategorizēja visus datortīklu procesus un tehnoloģijas 7 līmeņos un saskarnēs starp tiem. OSI modelis nodrošina garu sarakstu ar funkcijām un pakalpojumiem, kas var notikt katrā slānī. Tas arī apraksta katra slāņa mijiedarbību ar slāņiem tieši augšā un apakšā. OSI modelī slāņus mēdz saukt pēc to cipariem, piemēram, 7. slānis, lai teiktu lietojuma slānis. Tas ļāva datortīklu kompānijām ražot savietojamus tehnoloģiskos risinājumus. OSI modelis ir kļuvis par galveno datortīklu saziņas modeli.</span></p>
      <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Septini OSI atsauces modeļa līmeņi(no augšas uz leju):</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>7. Lietojuma(Application) – Lietojuma slānis satur protokolus, kurus izmanto process-to-process komunikācijā.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>6. Prezentācijas(Presentation) – Prezentācijas slānis nodrošina datu, kuri pārsūtīti &nbsp;starp lietojuma slāņa pakalpojumiem(services), kopēju reprezentāciju.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>5. Sesijas(Session) – Sesijas slānis nodrošina pakalpojumus prezentācijas slānim, lai organizētu tā dialogu un lai pārvaldītu datu apmaiņu.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>4. Transporta – Transporta slānis definē pakalpojumus, lai segmentētu, pārsūtītu un samontētu datus inviduālām komunikācijām starp beigu iekārtām.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>3. Tīkla(Network) – Tīkla slānis nodrošina pakalpojumus, lai apmainītu inviduālas datu daļas cauri tīklam starp identificētām beigu iekārtām.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>2. Datu posma(Data link) – Datu posma slāņa protokoli apraksta metodes datu rāmju apmaiņai starp ierīcēm caur kopēju vidi.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>1. Fiziskais(Physical) – Fiziskā slāņa protokoli apraksta mehāniskās, elektriskās, funkcionālās un procedūras vajadzības, lai aktivizētu, saglabātu un deaktivizētu fiziskus savienojumus bitu pārsūtīšanai uz un no tīkla iekārtu.&nbsp;</span></p>
          </li>
        </ul>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Septiņi OSI modeļa līmeņi ir (no augšas uz leju):</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>7. Lietojumu (Application) – tīklu pakalpojumi programmatūrai</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>6. Prezentācijas (Presentation) – datu pārveidošana un atainošana</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>5. Sesijas (Session) – sesiju pārvaldība</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>4. Transporta (Transport) – saziņas integritāte virtuālos slēgumos</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>3. Tīkla (Network) – loģiskā adresācija, ceļu izvēle</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>2. Kanāla (Data link) – tiešā savienojuma kontrole, pieeja videi, fiziskā adresācija</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>1. Fiziskais (Physical) – signālu sūtīšana vidē</span></p>
          </li>
        </ul>
        <br />
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Datortīklu sadalīšana līmeņos sniedz&nbsp;</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>sekojošas priekšrocības</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>:</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>tā sadala saziņu sīkākās, labāk pārvaldāmās daļās;</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>tā standartizē tīklu komponentes, lai nodrošinātu vairāku ražotāju izstrādi un uzturēšanu;</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>tā ļauj dažāda veida aparatūrai un programmatūrai sadarboties;</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>tā novērš izmaiņu vienā līmenī ietekmi uz citiem līmeņiem;</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>tā sadala datortīklu procesus mazākās daļās, ļaujot vieglāk tos saprast.</span></p>
          </li>
        </ul>
        <h2>TCP/IP modelis</h2>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>TCP/IP modelis</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;TCP/IP protokola modelis starptīkla(internetwork) komunikācijām tika izmantots 1970. gadu sākumā un dažkārt ir saukts par Interneta modelo. Tas definē četras funkciju kategorijas, kurām jānotiek, lai komunikācija būtu veiksmīga. TCP/IP protocol kopuma arhitektūra seko šī modeļa struktūrai. Tādēļ Interneta modelis ir bieži saukts par TCP/IP modeli.ASV aizsardzības departaments izveidoja TCP/IP protokolu saimi, jo tā vēlējās izveidot tīklu, kas izturētu vissarežģītākās situācijas, pat atomkaru. Atšķirībā no daudzām tā laika datortīklu tehnoloģijām, TCP/IP bija atvērts standarts. Tas paātrināja tā attīstību.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>TCP/IP modelis:</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Lietojumu(Application) – Attēlo datus lietotājam, kā arī kontrolē kodēšanu un dialogus.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Transporta – Atbalsta komunikāciju starp dažādām iekārtām starp daudzveidīgiem tīkliem.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Interneta – Nosaka labāko ceļu cauri tīklam.</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Tīkla piekļuves(Network Access) – kontrolē aparatūras ierīces un vides, kas veido tīklu.</span></p>
          </li>
        </ul>
        <h2>Salīdzinājums</h2>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>OSI modelis ir drīzāk veids, kā raudzīties uz datortīklu procesiem. Bet TCP/IP modelis ir strādājoša tīkla reālu protokolu saime. Pie tam TCP/IP modelis ir radies krietni ātrāk par OSI modeli.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>OSI un TCP/IP modeļu salīdzinājums.</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Protokoli, kas veido TCP/IP protokolu saimi, var arī būt aprakstīti ar OSI atsauces modeli. OSI modelī, TCP/IP modeļa tīkla piekļuves slānis un lietojuma slānis ir tālāk sadalīti, lai aprakstītu atsevisķas funkcijas, kurām jānotiek šajos slāņos.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Tīkla piekļuves slānī, TCP/IP protkolu saime nenorāda kādus protokolus izmantot, kad sūta pāri fiziskajai videi; tas tikai apraskta nodošanu no interneta slāņa uz fiziskajiem tīkla protkoliem. OSI slāņi 1 un 2 apraksta vajadzīgās procedūras, lai piekļūtu videi un fizikālās vajadzības, lai sūtītu datus pāri tīklam. OSI 3. slānis, Tīkla slānis, savienojas tieši ar TCP/IP Interneta slāni. Šis slānis ir izmantots, lai aprakstītu protokolus, kuri adresē un maršrutē ziņas cauri starptīklam. OSI 4. slānis, transporta slānis, savienojas tieši ar TCP/IP Transporta slāni. Šis slānis apraksta vispārīgos pakalpojumus un funkcijas, kuras nodrošina pasūtīto un uzticamo datu piegādi starp avota un galamērķa hostiem. TCP/IP lietojuma slānis iekļauj daudzus protokolus, kas nodrošina specifisku funkicionalitāti dažādām beigu lietotāja lietotnēm. OSI modeļa slāņi 5, 6, un 7 ir izmantoti kā atsauces lietojuma programmatūras izveidotājiem un pārdevējiem, kas ražo produktus, kas strādā tīklos. Gan TCP/IP, gan OSI modeļi ir bieži izmantoti, lai atsauktos uz protokoliem dažādos slāņos. Tādēļ, ka OSI modelis atdala datu posma slāni no fiziskā slāņa, tas tiek bieži izmantots, lai atsauktos uz apakšējiem slāņiem.</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Līdzīgākais šiem modeļiem ir transporta un tīkla slāņi, bet abi modeļi atšķiras ar to kā tie attiecas uz slāņiem zem un virs tiem.</span></p>
    </div>
  );
}

export default Osi;
