import React from 'react';

function Osi() {
  return (
    <div className="EthernetProtokols">
      <h1>6.Ethernet protokols.</h1>
      <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ethernet</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;ir uz kadriem bāzētu datortīklu tehnoloģiju kopa, uz kurām balstās lielākā daļa lokālo tīklu. Šiem standartiem ir kopīgs (līdzīgs un savstarpēji atpakaļsavietojams) kanāla slāņa protokols un vēsturiski dažādi fiziskā slāņa savienojumu standarti (daži no tiem ir daļēji savstarpēji savietojami (piem 100mbit ierīces spēj darboties ar 10mbit standartu)). Sākotnējā ethernet versija darbojās ar ātrumu 10Mbit/s un tika standartizēta kā IEEE 802.3, tur lietoja koaksiālos kabeļus maģistrāles topoloģijā. Vēlāk izstrādāja variantu ar vītā pāra kabeļiem, šajiem lietoja zvaigznes topoloģiju. Lietojot šādus pašus kabeļus (tālākajiem standartiem palielinājās prasības pret kabeļa kvalitāti) izstrādāja 100mbit un 1000mbit standartus. Eksistē arī standarti, kur lieto optiskos kabeļus, tur arī tīkla topoloģija ir vai nu zvaigzne, vai arī point-to-point.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ethernet operē pēdējos 2 OSI modeļa līmeņos, proti "Fiziskajā" un Data Link līmenī. Ethernet pirmajā OSI līmenī ir iesaistīts signālos, bitu straumēs, kas ceļo pa pārraides vidi, fiziskajās komponentēs, kas nodod signālu pārraides videi, kā arī vairākās fiziskajās topoloģijās. 2. OSI līmenī Ethernet nodrošina saziņu ar augstākiem līmeņiem ar Logical Link Control (LLC), izmanto adresēšanas sistēmas, lai identificētu ierīces, freimo bitus, lai sakārtotu tos grupās, kā arī ar MAC palīdzību identificē pārraides avotu. Ethernet sadala Data Link slāni divos izteiktos apakšslāņos: Logical Link Control (LLC) apakšslānī un Media Access Control (MAC) apakšslānī. Ethernetam IEEE 802.2 standarts apraksta LLC funkcijas, bet 802.3 standarts MAC apakšslāņa un fiziskā līmeņa funkcijas. LLC paņem network protokola datus, kas parasti ir IPv4 pakete un pievieno kontrolinformāciju, kas palīdz nogādāt paketi līdz gala mērķim. Layer 2 komunicē ar augšējiem slāņiem izmantojot LLC. LLC tiek implementēts programmatūrā un ir neatkarīgs no fiziskā datora aprīkojuma. Datorā LLC var uzskatīt par Tīkla kartes (Network Interface Card(NIC)) draiveriem.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Media Access Control (MAC)</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;ir zemākais Ethernet apakšslānis Data Link slānī. MAC ir implementēts "dzelžos", tipiski tīkla kartē (NIC).&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Etherneta MAC apakšslānis ir primāri atbildīgs par divām lietām:</span></p>
        <ul style={{marginTop: 0, marginBottom: 0, paddingInlineStart: '48px'}}>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Datu enkapsulācija;</span></p>
          </li>
          <li dir="ltr" style={{listStyleType: 'disc', fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}>
            <p dir="ltr" style={{lineHeight: '1.295', textAlign: 'justify', marginTop: '0pt', marginBottom: '8pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Media Access Control. Media Access Control Kā vārds jau to norāda, tad MAC nodrošina datu nokļūšanu uz un no pārraides vides. Tai skaitā arī "freima" pārsūtīšanas inicializāciju un pārraides kļūdu labošanu.</span></p>
          </li>
        </ul>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Loģiskā topoloģija&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ethernet loģiskā topoloģija ir multi-access bus. Tas nozīmē, kas visas attiecīgā tīkla ierīces saņem vienas ierīces sūtīto "freimu".&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Tā kā visas ierīces saņem visus "freimus", ir nepieciešams noteikt vai attiecīgais "freims" ir domāts konkrētajai ierīcei. Tas tiek darīts pārbaudot "freimā" esošā mērķa MAC adresi un salīdzinot ar savējo.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ethernet arī nodrošina metodi, lai noteikti kā ierīces dala pieeju pārraides videi. Tīkla piekļuves metode klasiskajam Ethernetam ir Carrier Sense Multiple Access with Collision Detection (CSMA/CD).&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ethernet pirmsākumos tika izmantoti koaksiāli kabeļi, kur viens kabelis kalpoja kā mugurkauls, bet pārējie datori fiziski tika pieslēgti pie šī kabeļa. Vēlāk notika migrācija uz&nbsp;</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>hub'u</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;izmantošanu. Šis ļāva uzlabot tīklu fizisko veidošanu (pateicoties arī UTP kabeļu ieviešanai.), taču nenovērsa kolīziju problēmu, jo arī šāda tipa tīklam bija kopīgs kolīzijas domēns.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Nākamais solis Ethernet attīstībā bija&nbsp;</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>switch'u</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;izmantošana. Tā atrisināja problēmas, kas radās ar vienu kopīgu kolīzijas domēnu, brīžos kad tīklā darbojās vairākas ierīces un CSMA/CD protokols vairs nespēja tikt galā. Switchs spēj kontrolēt datu plūsmu, izolējot katru portu un sūtot freimu tikai tai ierīcei, kura ir norādīta kā mērķis. Šis attiecīgi samazina kolīziju iespējas. Vēlāk ieviestais pilnā dupleksa režīms, kad ierīces var sūtīt un saņemt informāciju reizē, palīdzēja nodrošināt šodien iespējamos datu pārraides ātrumus.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Gadījumos, kad pārraides vide ir kopīga, visām ierīcēm ir garantēta pieeja videi. Ja vairāk kā viena ierīce pārraida datus, fiziskie signāli sadursies un tīklam būs jāatgūstas, lai komunikācija varētu turpināties.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Lai nodrošinātu šādu funkcionalitāti tiek izmantots CSMA/CD protokols, kas ļauj ierīcēm darboties vienā kolīzijas domēnā un atrisināt radušās kļūdas.&nbsp;</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ja ir radusies situācija, kad tīklā ir notikusi kolīzija, un to ir uztvērušas raidošās ierīces, tiek izsūtīts bloķēšanas signāls, kas apziņo visas tīkla ierīces par notikušo kolīziju, un ierosina atkāpšanas (back-off) algoritmu, kas liek visām ierīcēm pārstāt sūtīt datus un nejauši izvēlētu laika periodu, kas ļauj kolīzijas signālam norimt.</span></p>

    </div>
  );
}

export default Osi;
