import React from 'react';

function Osi() {
  return (
    <div className="IPv6">
      <h1>9.IPv6 protokols.</h1>
      <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>IPv6</span><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>&nbsp;(interneta protokola versija 6) ir Interneta Protokola (IP) versija. Šī protokola versija tika izveidota pēc Interneta Protokola 4 versijas (IPv4). Tīkls darbojas, pārsūtot datus starp tīkla mezgliem (hosts) mazās pakotnēs, kuras tiek neatkarīgi pārsūtītas pa tīklu un attiecīgi tiek apzīmētas kā Starptautisks sakaru protokols, kurš ir zināms kā Interneta Protokols (IP).</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Jebkurš tīkla mezgls vai dators pieprasa Interneta Protokola (IP) adresi, lai būtu iespējams sazināties savā starpā. Strauji pieaugot interneta tīklam, ir izveidojusies nepieciešamība pēc jaunām interneta protokola adresēm, ko IPv4 vairs nespēj nodrošināt. IPv6 protokolu izveidoja Interneta Tehniskā Uzdevumu Grupa (IETF), lai atrisinātu izveidojušos IPv4 adrešu trūkuma problēmu, kas ir arī aprakstīts Interneta Standartu dokumentā RFC 2460, kas ticis publiskots 1998. gada decembrī. Kā Ipv4, tā arī IPv6 ir interneta slāņu protokols, kas paredzēts tīkla pakotņu komutāciju apvienošanai un end-to-end (beigas-līdz-beigas) datugrammu pārraides nodrošināšanu pa vairākiem interneta protokolu tīkliem.</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Kamēr Ipv4 izmanto 32 bitus priekš interneta protokola adresēm, kas attiecīgi ļauj izveidot 232(4,294,967,296) adrešu, IPv6 izmanto 128 bitu adreses, kas ļauj attiecīgi izveidot 2128 (3,4x1038) adrešu. Šī izplešanās, daudzo adrešu iespēja, sniedz daudz vairāk iespēju gan priekš dažnedažādām iekārtām, gan priekš vienkāršiem lietotājiem interneta tīklā. Piemēram, ir lielāka elastība, izveidojot jaunas adreses, kā arī tas ir liels pluss priekš maršrutēšanas plūsmas.</span></p>
        <p dir="ltr" style={{lineHeight: '1.2', textAlign: 'justify', marginTop: '0pt', marginBottom: '0pt'}}><span style={{fontSize: '12pt', fontFamily: 'Calibri,sans-serif', color: '#000000', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>IPv6 novērš, pirmkārt, nepieciešamību tulkot tīkla adreses (NAT), kas tika plaši izmantots kā mēģinājums atvieglot IPv4 adrešu izmelšanas problēmu. IPv6 ir iekļautas daudzas jaunas iespējas, kuras nebija iespējamas pie IPv4. Vienkāršība jaunu adrešu piešķiršanā, tīkla pārnumurēšanā un maršrutēšanas paziņojumos, kad mainās interneta savienojuma pakalpojumu sniedzēji. Interneta protokola 6 versijā apakštīkla lielums ir standartizēts. Protams, ka IPv6 arhitektūrā ir integrēta tīkla drošība un IPv6 specifikāciju pilnvarojums, kurš atbilst priekš IPsec kā savstarpējās izmantojamības fundamentālā nepieciešamība.</span></p>
    </div>
  );
}

export default Osi;
